<template>
  <h1 class="p-4 text-3xl text-gray-800">Help</h1>
  <p class="font-mono p-4">
    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quod reprehenderit error voluptatibus dicta fuga doloribus itaque expedita quas non similique dolorem dolore aut quisquam, placeat cum, et id animi consequuntur! Sit libero, hic sunt ducimus voluptatem eveniet, esse atque saepe alias in consectetur illum consequuntur odio, corrupti ipsum? Fugit, repellendus? Ab non nostrum, ea sed illum quo. Delectus deleniti veritatis consequuntur dignissimos provident doloribus a quibusdam doloremque quos explicabo deserunt obcaecati laborum odit officia soluta magnam beatae id distinctio itaque, quas numquam veniam sit praesentium. Dicta labore qui libero odit nihil nam, rem vel ex, itaque animi reiciendis quos? Tempora modi rerum quaerat. Dolores reiciendis natus, adipisci rem consequatur doloremque aliquam officiis cupiditate atque incidunt dicta ea neque aperiam aliquid quasi sunt maxime sit eligendi laboriosam esse non. Dolorum mollitia repudiandae quaerat numquam accusantium laborum optio nihil nam autem quibusdam minus provident ad quo aliquam placeat, quos id consequatur qui animi in excepturi tempora. Nesciunt nostrum aut harum consequuntur sed tempore quidem vel doloremque sapiente cumque fugiat, soluta eaque dolor repellat ut libero sint atque dicta voluptas beatae, facere molestiae expedita. Dolorum corrupti sed quidem molestias voluptates tempore voluptatum, voluptate numquam temporibus impedit corporis, quas ratione magnam quia cum? Error minus quia beatae magni saepe quisquam non, odio vel molestias fugiat ea neque delectus obcaecati repellat tempora temporibus expedita! Dolor possimus modi ex corrupti nisi repellat veniam, deserunt assumenda veritatis, natus nobis suscipit velit maiores eius officiis non, quae distinctio iure voluptate dicta commodi molestias atque inventore? Laudantium quasi ducimus recusandae amet dicta fugiat reprehenderit beatae quas eum temporibus. Illo cum temporibus laboriosam repellat, inventore fugit excepturi exercitationem quaerat unde architecto nostrum quae eos dolor voluptatibus odio maxime perferendis eius error dolores consectetur est at minima. Dolore non quis iure labore qui modi, doloribus at aliquam rerum voluptatem, aperiam error.
  </p>
  <div class="p-4 text-3xl font-bold text-indigo-700">
    {{ $store.state.brand }}
  </div>
</template>
